devel/boehm-gc updated with Capable VMs bdwgc Morello port
CTSRD-CHERI/cheribsd-ports pull request #151
Opened 2024-03-12 15:53 UTC by jeremysinger

We switched to using our CapableVMs fork of the Boehm-Demers-Weiser collector, which compiles and runs on Morello CheriBSD

2024-03-14 11:37 UTC, jeremysinger commented
hi @kwitaszczyk Duncan suggested that you might prefer us to name this package boehm-gc-cheri since it is a specific fork of the original boehm-gc which runs ok in hybrid mode. Our code has not been upstreamed to the official bdwgc github repo.

2024-03-14 11:44 UTC, kwitaszczyk commented
@jeremysinger Yes, we briefly discussed this yesterday. You can either duplicate code under a *-cheri port but it would be preferable to create a port that reuses the upstream port with some modifications. You can have a look at devel/gdb and devel/gdb-cheri (https://github.com/CTSRD-CHERI/cheribsd-ports/pull/130) for suggestions how to do that. However, it might turn out that the upstream and *-cheri ports differ significantly and then it wouldn't make sense to reuse the upstream port.

2024-03-15 12:58 UTC, kwitaszczyk requested changes
Let's mark this as waiting for the port's name change.

2024-03-15 17:29 UTC, jeremysinger commented
hi @kwitaszczyk yes we will change the name to boehm-gc-cheri. I had a chat with @djichthys and we are quite far behind upstream bdwgc - we want to rebase but we don't have resource for this right now - hopefully a summer project :-)

2024-06-13 12:09 UTC, kwitaszczyk commented
@jeremysinger Any update on this?

2025-06-05 08:06 UTC, closed without merging