Disable gobject-introspection for purecap ABI.
CTSRD-CHERI/cheribsd-ports pull request #167
Opened 2024-07-12 08:45 UTC by gcjenkinson

gobject-introspection is dependent of support in libffi for ffi closures, which is current missing for the the purecap ABI. Although the dependency on g-ir-scanner is build time dependency it requires ABI compatability so it is not possible to use the hybrid gobject-introspection package. Therefore, support for introspection is disbaled.

As introspection is used solely for generating documentation and the purecap ABI disables the DOCS option by default, disabling gobject-introspection has no impact at present.  However, it is somewhat disruptive as it requires modifications to the pkg-plist of various ports.

Disable gobject-introspection for gtk30 deps.

librsvg2 requires building with the VAPI (Vala API) option unset. The Vala API is generated with gobject-introspection which isn't currently supported for purecap (due to its dependency on ffi closure support in libffi).

2024-07-12 12:29 UTC, kwitaszczyk requested changes
I think it would be good to change the approach towards modifying `USE_GNOME`. Other comments are optional. However, with the optional changes, we would get rid of all changes to `Makefile` files and we would only have changes in `Mk/Uses/gnome.mk` and `pkg-plist` files.

2024-07-12 12:29 UTC, kwitaszczyk commented on devel/gsettings-desktop-schemas/Makefile
> -USE_GNOME=	glib20 introspection:build
Here and in other places, could you set `USE_GNOME` to `glib20` and other components that are used in both purecap and non-purecap cases and later remove `introspection:build` from `USE_GNOME` using `USE_GNOME= ${USE_GNOME:Nintrospection:build}`? Thanks to that, we will not have any conflicts in future upstream merges.

If you would like to, you could modify `Mk/Uses/gnome.mk` to implement this logic there. However, it would be good to print a warning informing a user that we automatically disable `introsection:build` for purecap if you decide to move it there. I'd be fine with keeping this logic in port's Makefile files if you decide not to modify `Mk/Uses/gnome.mk`.

2024-07-12 12:29 UTC, kwitaszczyk commented on devel/gsettings-desktop-schemas/Makefile
> +MESON_ARGS+=	-Dintrospection=false
If you would like to, you could modify `Mk/Uses/gnome.mk` to append this value to `MESON_ARGS` if `USES` includes `meson` and `USE_GNOME` doesn't include `introspection:build`. Regardless of your decision here, I'm fine with this version.

2024-07-12 12:29 UTC, kwitaszczyk commented on devel/gsettings-desktop-schemas/Makefile
> +PLIST_SUB+=	GIR="@comment "
Similarly to the previous comment, you could modify `Mk/Uses/gnome.mk` to append this to `PLIST_SUB` if `USE_GNOME` doesn't include `introsection:build`. Again, I'm fine with this version if you decide not to change this.

2024-07-12 12:29 UTC, kwitaszczyk commented on sysutils/polkit/Makefile
> -		-Dintrospection=true \
It would be worth checking if `MESON_ARGS= (...) -Dintrospection=true -Dintrospection=false` would work. If so, we could leave this line here not to introduce a conflict against upstream.

2024-07-12 14:34 UTC, gcjenkinson commented on devel/gsettings-desktop-schemas/Makefile
> -USE_GNOME=	glib20 introspection:build
This produces a recursive use of the variable. I've reinstated the original `USE_GNOME` to minimise the diff with upstream and then I overwrite it for purecap without introspection. Trying to set `USE_GNOME=${USE_GNOME:Nintrospection:build}` I get the following:

`Variable USE_GNOME is recursive.`

2024-07-12 15:50 UTC, kwitaszczyk commented on devel/gsettings-desktop-schemas/Makefile
> -USE_GNOME=	glib20 introspection:build
Apologies for misleading you. Does `USE_GNOME:=   ${USE_GNOME:Nintrospection\:build}` work (note `:=` and `\:`).

2024-07-12 15:54 UTC, gcjenkinson commented on devel/gsettings-desktop-schemas/Makefile
> -USE_GNOME=	glib20 introspection:build
Ah great, yes that works. The changes are now minimal I think. I moved the MESON_ARGS to gnome.mk and each individual Makefile will just have the remove to `introspection:build`. I'll push again once I've check all the changes.

2024-07-17 09:37 UTC, gcjenkinson commented on sysutils/polkit/Makefile
> -		-Dintrospection=true \
I've checked this at it seems to work so I reinstated the "-Dintrospection=true" arg.

2024-07-17 12:08 UTC, kwitaszczyk commented on devel/libgusb/Makefile
> +USE_GNOME=	glib20 introspection:build
Could you revert this and other unnecessary changes that move lines or introduce empty lines?

2024-07-17 14:30 UTC, kwitaszczyk commented on Mk/Uses/gnome.mk
> +DISABLE_INTROSPECTION?= false
What about defining it as `introspection_MESON_ARG`, similarly to `introspection_BUILD_DEPENDS` and other variables?

Then:
```suggestion
introspection_MESON_ARG?= false
MESON_ARGS+=	-Dintrospection=${introspection_MESON_ARG}
```

2024-07-17 14:52 UTC, jrtc27 commented on Mk/Uses/gnome.mk
> +DISABLE_INTROSPECTION?= false
The ARG helps, but now that just sounds like introspection_MESON_ARG=true would properly enable introspection, yet plist substitution will comment out %%GIR%% lines... you still need a DISABLE in there

2024-07-22 16:30 UTC, kwitaszczyk commented on Mk/Uses/gnome.mk
> +DISABLE_INTROSPECTION?= false
What about the current version that excludes from from plist if introspection_MESON_ARG is set to false or disabled?

2024-07-25 14:06 UTC, kwitaszczyk commented on Mk/Uses/gnome.mk
> +DISABLE_INTROSPECTION?= false
Let's work on further improvements independently, if needed, not to block this PR.

2024-07-25 14:06 UTC, kwitaszczyk approved these changes
Thank you for working on this!

2024-07-25 14:06 UTC, merged