lang/go: Add Go 1.21 port from upstream and bump default version
CTSRD-CHERI/cheribsd-ports pull request #171
Opened 2024-08-05 14:55 UTC by RoundofThree

* Cherry-pick go121 from upstream
* Apply the same patches as in #156
* Bump the default go version to 1.21 (matching upstream)

2024-08-05 15:38 UTC, brooksdavis commented
Please redo the cherry-picks with the -x option so the upstream commit is recorded.

2024-10-28 12:43 UTC, kwitaszczyk requested changes

2024-10-28 12:43 UTC, kwitaszczyk commented on Mk/bsd.default-versions.mk
> +GO_DEFAULT?=		1.21
Instead, could you `cherry-pick -x a5a000df3b3697665460dbfbafe7120e306d8913` but only changes related to this file?

Note that changing a default version requires bumping all ports' versions that use the port for which you bump the default version. We should cherry-pick all changes from a5a000df3b3697665460dbfbafe7120e306d8913 here but we are many commits behind the upstream. We could bump `PORTVERVISION` of all ports mentioned in a5a000df3b3697665460dbfbafe7120e306d8913 by 1 but then we would create conflicts when merging changes from upstream.

Next time we build packages, we will bump `__CheriBSD_version` and a user will be requested to upgrade their packages due to the difference in the ABI. Hence, it is not crucial to do it completely by the book here.

2024-10-28 12:43 UTC, kwitaszczyk commented on Mk/bsd.default-versions.mk
> +# Possible values: 1.18, 1.19, 1.20, 1.21, -devel
It doesn't seem to be needed. It looks like `1.21-devel` here aims to suggest that `lang/go-devel` is a future `1.21` version. Note that `Mk/Uses/go.mk` removes the version from this string with:
```
GO_SUFFIX=      ${GO_VERSION:S/.//:C/.*-devel/-devel/}
```
Instead, this comment should be updated when a developer updates `lang/go-devel`, which isn't included in this PR. With this PR, `lang/go-devel` remains (hopefully) to be some revision of `1.21`.

2024-10-28 14:37 UTC, kwitaszczyk approved these changes

2024-10-28 14:38 UTC, kwitaszczyk commented
I won't backport it to 24.05 but the next package repository for dev will include this change.

2024-10-28 14:38 UTC, merged