Target fixes and bash
CTSRD-CHERI/cheribsd-ports pull request #24
Opened 2022-06-22 22:52 UTC by brooksdavis

A set of fixes to make the target triple not include the `c` suffix on CheriABI.

Also, a set of patches to allow bash to compile natively. Long the way I had to fix issues in GNU m4.

2022-07-21 17:13 UTC, brooksdavis commented
@kwitaszczyk, will my proposed revert of 99152dd1d7ed1629153bca2ac4190e2859309c61 cause problems now that we're generating the correct triple?

2022-07-25 21:25 UTC, kwitaszczyk requested changes
> @kwitaszczyk, will my proposed revert of [99152dd](https://github.com/CTSRD-CHERI/cheribsd-ports/commit/99152dd1d7ed1629153bca2ac4190e2859309c61) cause problems now that we're generating the correct triple?

It looks good and shouldn't cause problems. I will revert `CONFIGURE_TARGET_TRIPLE` in CTSRD-CHERI/poudriere-infrastructure.

The typo in `riscv64c` is only preventing us from merging this change to main. Note that `files/cheribsd.patch` is automatically used after all patches from `files/`. We should decide if we want to follow that approach for all ports and use a single patch for all CheriBSD/CHERI-related changes.

2022-07-25 21:25 UTC, kwitaszczyk commented on Mk/bsd.ssp.mk
> +    (! ${ARCH:Mmips*}) && ${ARCH} != aarch64c && ${ARCH} != risc64c
Typo:
```suggestion
    (! ${ARCH:Mmips*}) && ${ARCH} != aarch64c && ${ARCH} != riscv64c
```

2022-07-25 21:25 UTC, kwitaszczyk commented on Templates/config.guess
> +	    exit ;;
It would be better to update `UNAME_PROCESSOR` and not duplicate the `echo` line in case it's changed in upstream. We'd need to update it in our fork as well.
```suggestion
	    UNAME_PROCESSOR=${UNAME_PROCESSOR%c} ;;
```

2022-07-27 10:47 UTC, kwitaszczyk requested changes

2022-07-27 10:47 UTC, kwitaszczyk commented on Mk/bsd.ssp.mk
> +    (! ${ARCH:Mmips*}) && ${ARCH} != aarch64c && ${ARCH} != risc64v
```suggestion
    (! ${ARCH:Mmips*}) && ${ARCH} != aarch64c && ${ARCH} != riscv64c
```

2022-07-27 16:44 UTC, brooksdavis commented on Mk/bsd.ssp.mk
> +    (! ${ARCH:Mmips*}) && ${ARCH} != aarch64c && ${ARCH} != risc64v
*sigh* hopefully actually fixed.

2022-07-27 16:50 UTC, kwitaszczyk approved these changes

2022-07-27 17:08 UTC, merged