graphics/libdrm: add cheribsd support.
CTSRD-CHERI/cheribsd-ports pull request #46
Opened 2022-08-11 17:03 UTC by bukinr

Obtained from 1.

[1]. https://github.com/bukinr/mesa-drm/tree/main
commit # 480df36b8dc2f922351f167cdf3706619c23b258

2022-09-14 12:39 UTC, kwitaszczyk requested changes

2022-09-14 12:39 UTC, kwitaszczyk commented on devel/kf5-kio/Makefile
> +USES+=		desktop-file-utils gnome
I wonder in what cases an excluded USE should become a disabled option. Do you have any thoughts on that?

2022-09-14 12:39 UTC, kwitaszczyk commented on Mk/Uses/cmake.mk
> +CMAKE_ARGS+=	-DGETTEXT_MSGFMT_EXECUTABLE=/usr/local64/bin/msgfmt
This should be moved after
```
.f !defined(_INCLUDE_USES_CMAKE_MK)
 _INCLUDE_USES_CMAKE_MK=	yes
```
and even better next to `CMAKE_ARGS`, only for a CheriABI build and using a predefined LOCALBASE64 instead of hardcoding a path:
```
.if ${ARCH:Mpurecap}
CMAKE_ARGS+=    -DGETTEXT_MSGFMT_EXECUTABLE=${LOCALBASE64}/bin/msgfmt
.endif
```
However, `msgfmt` is not always required. It should be required when `gettext-tools` is added to `USES`. It would be better to move this logic to `Mk/Uses/gettext-tools.mk` with a condition that `cmake` is also used, i.e.:
```
.if ${USES:Mcmake} && ${ARCH:Mpurecap}
CMAKE_ARGS+=    -DGETTEXT_MSGFMT_EXECUTABLE=${LOCALBASE64}/bin/msgfmt
.endif
```

This logic assumes that you have a hybrid ABI msgfmt installed which is not true when building packages and possibly when a user wants to build ports manually. In order to use a hybrid ABI msgfmt, we must mark `devel/gettext-tools` as broken for purecap and allow to use a replacement hybrid ABI package instead, i.e. in `devel/gettext-tools/Makefile`, add:
```
BROKEN_purecap=   msgfmt is broken for CheriABI
USE_PKG64=        1
```

2022-09-14 12:39 UTC, kwitaszczyk commented on devel/libudev-devd/files/cheribsd.patch
> ++	return (0);
There should be a comment explaining this change, and possibly a better solution that removes the whole function contents, including an unused `ule` variable.

2022-09-14 12:39 UTC, kwitaszczyk commented on devel/qt5/files/extrapatch-cheribsd.patch
> ++#!/usr/local64/bin/perl
Have you verified if it breaks with the current CheriABI Perl that had several CheriABI-related issues solved?

2022-09-14 12:39 UTC, kwitaszczyk commented on graphics/libepoxy/Makefile
> +OPTIONS_DEFAULT=	X11 EGL
We should alphabetically sort such lists.

2022-09-14 12:39 UTC, kwitaszczyk commented on graphics/libepoxy/Makefile
> +OPTIONS_DEFAULT=	X11 EGL
Should `EGL` be enabled for `aarch64` and `aarch64c` or all architectures? We should consider what CheriBSD-specific changes should be upstreamed.

2022-09-14 12:39 UTC, kwitaszczyk commented on textproc/kf5-syntax-highlighting/Makefile
> +CMAKE_ARGS+=	-DPERL_EXECUTABLE=/usr/local64/bin/perl
Have you tried CheriABI Perl after recent fixes?

2022-09-14 12:39 UTC, kwitaszczyk commented on x11-fonts/fontconfig/files/cheribsd.patch
> ++/* TODO: add cheri support. */
I have added CheriABI changes for fontconfig in `main`.

2022-10-04 21:38 UTC, closed without merging

2022-10-06 15:18 UTC, bukinr commented on x11-fonts/fontconfig/files/cheribsd.patch
> ++/* TODO: add cheri support. */
Sounds good. I tried it works!

2022-10-06 22:24 UTC, kwitaszczyk commented on devel/kf5-kio/Makefile
> +OPTIONS_EXCLUDE_riscv64c=	DOCBOOK
As discussed, it's not in CheriBSD ports yet but will be added.