devel/protobuf: Initial set of cheri fixes
CTSRD-CHERI/cheribsd-ports pull request #90
Opened 2023-04-05 15:27 UTC by gcjenkinson

A set of very explicit changes for CHERI. Some of the changes are required due to the reluctance to provide alignment greater that 8 bytes assumed by ubsan and tcmalloc debug allocation logic.

With these changes the protobuf port compiles but as the package archive does not contain the git submodules the tests cannot be ran.

2023-04-05 15:29 UTC, gcjenkinson commented
FYI the changes I have made to protobuf. I'll have another look if I can minimise the set of changes required to suppress warnings about ambiguous provenance, these warnings are benign so it seems overly disruptive to have conditional code with different types.

2023-04-05 15:44 UTC, gcjenkinson commented
I've tried compiling mysql80-server and I get a Bus error running the protobuf compiler. So there's clearly more work required here.

2023-04-12 14:45 UTC, qwattash commented on devel/protobuf/files/cheribsd.patch
> ++  GOOGLE_LOG(FATAL) << "Unaligned (" << align << ") access at " << (size_t) address;
should the cast be a `ptraddr_t`?

2023-04-12 14:50 UTC, gcjenkinson commented on devel/protobuf/files/cheribsd.patch
> ++  GOOGLE_LOG(FATAL) << "Unaligned (" << align << ") access at " << (size_t) address;
Yes that'd make more sense.

2024-07-01 14:12 UTC, kwitaszczyk commented
@gcjenkinson Is it still a draft?

2024-07-10 12:32 UTC, gcjenkinson commented
I've lost a bit of the context here, but the changes produce a working protobuf and shouldn't be too controversial.

2024-07-10 12:36 UTC, kwitaszczyk commented
I'm fine with merging cheribsd.patch as is. The code is appropriately annotated and shouldn't break aarch64 packages. Could you squash commits and reference a repository that includes these changes in a commit message?

FYI, I'd expect PRs in CheriBSD ports to review changes specific to ports. I think a review of patches in port's source code would work better as part of a PR in a port-specific repository.

2024-07-12 14:02 UTC, kwitaszczyk requested changes
I have just noticed that your branch is based on an older revision without `Makefile.purecap`. Could you rebase it and remove `Makefile.purecap` to indicate this port is ready for CheriABI now?

Also, could you fix the commit message not to suggest the patch is for the version 3.21.12 of CheriBSD?

2024-07-12 15:41 UTC, kwitaszczyk approved these changes
Looks good. Thank you!

2024-07-12 15:46 UTC, merged